import type { PlayerConfigType } from '../types/players'

const playerConfig: PlayerConfigType = {
  RickDefault: {
    type: 'RickDefault',
    title: 'Обычный Рик',
    regeneration: 0,
    maximumHitPoints: -20,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol',
    evolutions: ['MemoryRick', 'RickDoofus', 'RickBald', 'TinyRick'],
  },
  CommanderRick: {
    type: 'CommanderRick',
    title: 'Командир Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine3',
    evolutions: [],
  },
  CopRick: {
    type: 'CopRick',
    title: 'Полицейский Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol2',
    evolutions: ['RickSupremeGuard'],
  },
  CrowRick: {
    type: 'CrowRick',
    title: 'Вороний Рик',
    regeneration: 0,
    maximumHitPoints: 300,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'MachineGun3',
    evolutions: [],
  },
  D99Rick: {
    type: 'D99Rick',
    title: 'D-99 Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle3',
    evolutions: [],
  },
  DeepthroatRick: {
    type: 'DeepthroatRick',
    title: 'Информатор Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle2',
    evolutions: ['D99Rick', 'RickGuard'],
  },
  FederationPrisonRick: {
    type: 'FederationPrisonRick',
    title: 'Заключенный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol1',
    evolutions: ['CopRick'],
  },
  GeneralRick: {
    type: 'GeneralRick',
    title: 'Генерал Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine2',
    evolutions: ['RickSpaceSuit', 'CommanderRick', 'RickWarrior'],
  },
  GhostcatcherRick: {
    type: 'GhostcatcherRick',
    title: 'Рик - ловец призраков',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun2',
    evolutions: ['RickGuard'],
  },
  MemoryRick: {
    type: 'MemoryRick',
    title: 'Рик памяти',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: -1,
    bulletSpeed: 0,
    bulletDamage: 5,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol',
    evolutions: [
      'FederationPrisonRick',
      'RickVapourWave',
      'RickZarchez',
      'PickleRick',
    ],
  },
  PickleRick: {
    type: 'PickleRick',
    title: 'Огурчик Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RatSuitPickleRick'],
  },
  RaderRick: {
    type: 'RaderRick',
    title: 'Рейдер Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun1',
    evolutions: ['GhostcatcherRick'],
  },
  RatSuitPickleRick: {
    type: 'RatSuitPickleRick',
    title: 'Огурчик Рик в крысином костюме',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver3',
    evolutions: ['SpiritualLeaderRick', 'CrowRick'],
  },
  Rick800: {
    type: 'Rick800',
    title: 'Рик 800',
    regeneration: 0,
    maximumHitPoints: 1500,
    bodyDamage: 50,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 100,
    weapon: 'Hand',
    evolutions: [],
  },
  RickBald: {
    type: 'RickBald',
    title: 'Лысый Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: -1,
    attackRate: 10,
    speed: 0,
    weapon: 'SubmachineGun',
    evolutions: ['WeirdRick', 'RickJunkYard', 'RickFlatTop', 'PickleRick'],
  },
  RickBeefcake: {
    type: 'RickBeefcake',
    title: 'Качок Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['Rick800'],
  },
  RickDoofus: {
    type: 'RickDoofus',
    title: 'Балбес Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 30,
    bulletDamage: 10,
    attackRate: 0.9,
    speed: 0,
    weapon: 'Rifle',
    evolutions: ['WastelandRick', 'SherlockRick', 'RaderRick', 'PickleRick'],
  },
  RickDude: {
    type: 'RickDude',
    title: 'Чувак Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster2',
    evolutions: ['RickMiami'],
  },
  RickEvil: {
    type: 'RickEvil',
    title: 'Злой Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol1',
    evolutions: ['RickTurberlent', 'RickShibuya'],
  },
  RickFlatTop: {
    type: 'RickFlatTop',
    title: 'Плоско стриженный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'SubmachineGun1',
    evolutions: ['RickMurderPatrol'],
  },
  RickGreaser: {
    type: 'RickGreaser',
    title: 'Стиляга Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken1',
    evolutions: ['RickKarate', 'RickTurberlent'],
  },
  RickGuard: {
    type: 'RickGuard',
    title: 'Охранник Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'GaussGun3',
    evolutions: [],
  },
  RickJohnRick: {
    type: 'RickJohnRick',
    title: 'Рик Джон',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver3',
    evolutions: [],
  },
  RickJunkYard: {
    type: 'RickJunkYard',
    title: 'Рик со свалки',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Machine1',
    evolutions: ['GeneralRick'],
  },
  RickKarate: {
    type: 'RickKarate',
    title: 'Каратист Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken2',
    evolutions: ['RickNinja'],
  },
  RickMiami: {
    type: 'RickMiami',
    title: 'Рик с Майами',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster3',
    evolutions: [],
  },
  RickMurderPatrol: {
    type: 'RickMurderPatrol',
    title: 'Дозорный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'SubmachineGun2',
    evolutions: ['RickWarrior'],
  },
  RickNinja: {
    type: 'RickNinja',
    title: 'Ниндзя Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Shuriken3',
    evolutions: [],
  },
  RickRobot: {
    type: 'RickRobot',
    title: 'Робот Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'RocketGun3',
    evolutions: [],
  },
  RickShibuya: {
    type: 'RickShibuya',
    title: 'Сибуйский Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol2',
    evolutions: ['RickRobot', 'Rick800'],
  },
  RickSmooth: {
    type: 'RickSmooth',
    title: 'Шикарный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver2',
    evolutions: ['RickJohnRick'],
  },
  RickSpaceSuit: {
    type: 'RickSpaceSuit',
    title: 'Рик в скафандре',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'PlasmoGun3',
    evolutions: [],
  },
  RickSupremeGuard: {
    type: 'RickSupremeGuard',
    title: 'Верховный страж Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Pistol3',
    evolutions: [],
  },
  RickSurvivor: {
    type: 'RickSurvivor',
    title: 'Выживший Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle2',
    evolutions: ['D99Rick'],
  },
  RickTurberlent: {
    type: 'RickTurberlent',
    title: 'Рик с турбулентным соком',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RickNinja', 'RickRobot'],
  },
  RickValentinesDay: {
    type: 'RickValentinesDay',
    title: 'Связанный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: ['RickBeefcake'],
  },
  RickVapourWave: {
    type: 'RickVapourWave',
    title: 'Нереальный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 10,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster1',
    evolutions: ['RickDude'],
  },
  RickWarrior: {
    type: 'RickWarrior',
    title: 'Вояка Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'MachineGun3',
    evolutions: [],
  },
  RickZarchez: {
    type: 'RickZarchez',
    title: 'Рик Зарчез',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Revolver1',
    evolutions: ['RickSmooth'],
  },
  SherlockRick: {
    type: 'SherlockRick',
    title: 'Шерлок Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 1,
    bulletDamage: 20,
    attackRate: 0,
    speed: -10,
    weapon: 'Rifle1',
    evolutions: ['DeepthroatRick'],
  },
  SpaceTrooperRick: {
    type: 'SpaceTrooperRick',
    title: 'Космический десантник Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'PlasmoGun2',
    evolutions: ['RickSpaceSuit'],
  },
  SpiritualLeaderRick: {
    type: 'SpiritualLeaderRick',
    title: 'Духовный лидер Рик',
    regeneration: 0,
    maximumHitPoints: 300,
    bodyDamage: 10,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Hand',
    evolutions: [],
  },
  TinyRick: {
    type: 'TinyRick',
    title: 'Крошка Рик',
    regeneration: 0,
    maximumHitPoints: -50,
    bodyDamage: -0.1,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 10,
    speed: 20,
    weapon: 'Pistol',
    evolutions: ['RickGreaser', 'RickEvil', 'RickValentinesDay', 'PickleRick'],
  },
  WastelandRick: {
    type: 'WastelandRick',
    title: 'Пустырный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Rifle1',
    evolutions: ['RickSurvivor'],
  },
  WeirdRick: {
    type: 'WeirdRick',
    title: 'Странный Рик',
    regeneration: 0,
    maximumHitPoints: 0,
    bodyDamage: 0,
    bulletSpeed: 0,
    bulletDamage: 0,
    attackRate: 0,
    speed: 0,
    weapon: 'Blaster1',
    evolutions: ['SpaceTrooperRick'],
  },
}

export default playerConfig
